#pragma once

#include <sys/socket.h>
#include <iostream>
#include <iomanip>
#include <netinet/in.h>
#include <fcntl.h>
#include <unistd.h>
#include <cstring>
#include <cstdio>
#include <stdlib.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#include <fstream>
#include <map>
#include "CGIresponse.hpp"
#include <vector>
#include <string>
#include <ctime>
#include "Response.hpp"
#include <dirent.h>
#include <algorithm>